package edu.berkeley.cs.cs162;

/**
 * 
 * @author jortiz
 *
 */
public enum MessageType {
	CONNECT,
	CONNECT_OK,
	CONNECT_REJECTED,
	DISCONNECT,
	DISCONNECT_OK,
	LOGIN,
	LOGIN_OK,
	LOGIN_REJECTED,
	LOGIN_QUEUED,
	LOGOUT,
	LOGOUT_OK,
	JOIN_GROUP,
	JOIN_GROUP_OK_CREATE,
	JOIN_GROUP_OK_JOIN,
	JOIN_GROUP_BAD_GROUP,
	JOIN_GROUP_FAIL_FULL,
	LEAVE_GROUP,
	LEAVE_GROUP_OK,
	LEAVE_GROUP_BAD_GROUP,
	LEAVE_GROUP_NOT_MEMBER,
	SEND_MSG,
	SEND_MSG_OK,
	SEND_MSG_BAD_DEST,
	SEND_MSG_FAIL,
	SEND_ACK_FAILED,
	READ_LOG,
	ADD_USER,
	ADD_USER_OK,
	ADD_USER_REJECTED,
	INVALID_STATE
}
